# Generated by Django 3.1 on 2021-09-28 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sjxf', '0005_auto_20210927_1709'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklist',
            name='v_flag',
        ),
        migrations.AddField(
            model_name='tasklist',
            name='celery_task_id',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Celery任务号'),
        ),
        migrations.AlterField(
            model_name='tasklist',
            name='status',
            field=models.CharField(choices=[('0', '已提交'), ('1', '执行中'), ('2', '执行完成'), ('3', '执行失败'), ('4', '已取消')], max_length=1, verbose_name='任务状态'),
        ),
    ]
